<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="1" failures="0" hostname="PC-20170621WOWM" name="pytest" skipped="0" tests="4" time="46.532" timestamp="2020-07-15T15:33:08.506024"><testcase classname="test_dir.interface.test_all_order_query_page" file="test_dir\interface\test_all_order_query_page.py" line="9" name="test_login" time="0.001"></testcase><testcase classname="test_dir.interface.test_all_order_query_page.TestQuery" file="test_dir\interface\test_all_order_query_page.py" line="17" name="test_query" time="0.076"></testcase><testcase classname="test_dir.interface.test_login" file="test_dir\interface\test_login.py" line="12" name="test_login" time="5.429"></testcase><testcase classname="pytest" name="internal" time="0.000"><error message="internal error">Traceback (most recent call last):
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\_pytest\main.py&quot;, line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\_pytest\main.py&quot;, line 235, in _main
    config.hook.pytest_runtestloop(session=session)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\manager.py&quot;, line 87, in &lt;lambda&gt;
    firstresult=hook.spec.opts.get(&quot;firstresult&quot;) if hook.spec else False,
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\callers.py&quot;, line 208, in _multicall
    return outcome.get_result()
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\callers.py&quot;, line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\_pytest\main.py&quot;, line 256, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\manager.py&quot;, line 87, in &lt;lambda&gt;
    firstresult=hook.spec.opts.get(&quot;firstresult&quot;) if hook.spec else False,
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\callers.py&quot;, line 208, in _multicall
    return outcome.get_result()
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\callers.py&quot;, line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pytest_rerunfailures.py&quot;, line 176, in pytest_runtest_protocol
    reports = runtestprotocol(item, nextitem=nextitem, log=False)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\_pytest\runner.py&quot;, line 89, in runtestprotocol
    rep = call_and_report(item, &quot;setup&quot;, log)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\_pytest\runner.py&quot;, line 178, in call_and_report
    report = hook.pytest_runtest_makereport(item=item, call=call)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\manager.py&quot;, line 87, in &lt;lambda&gt;
    firstresult=hook.spec.opts.get(&quot;firstresult&quot;) if hook.spec else False,
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\pluggy\callers.py&quot;, line 203, in _multicall
    gen.send(outcome)
  File &quot;D:\pycham\newSgTestForAll\conftest.py&quot;, line 53, in pytest_runtest_makereport
    capture_screenshots(case_name)
  File &quot;D:\pycham\newSgTestForAll\conftest.py&quot;, line 100, in capture_screenshots
    base.driver.save_screenshot(image_dir)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py&quot;, line 1055, in save_screenshot
    return self.get_screenshot_as_file(filename)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py&quot;, line 1032, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py&quot;, line 1064, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode(&apos;ascii&apos;))
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py&quot;, line 1074, in get_screenshot_as_base64
    return self.execute(Command.SCREENSHOT)[&apos;value&apos;]
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py&quot;, line 321, in execute
    self.error_handler.check_response(response)
  File &quot;C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py&quot;, line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=74.0.3729.169)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.1.7601 SP1 x86_64)</error></testcase></testsuite></testsuites>