<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="2" failures="0" hostname="WIN-CDD40IFICEH" name="pytest" skipped="0" tests="2" time="0.235" timestamp="2020-06-16T00:05:56.294525"><testcase classname="" file="test_dir/test_login.py" name="test_dir.test_login" time="0.000"><error message="collection failure">Fixture &quot;browser&quot; called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.</error></testcase><testcase classname="pytest" name="internal" time="0.000"><error message="internal error">Traceback (most recent call last):
  File &quot;D:\python3\lib\site-packages\_pytest\main.py&quot;, line 191, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File &quot;D:\python3\lib\site-packages\_pytest\main.py&quot;, line 234, in _main
    config.hook.pytest_collection(session=session)
  File &quot;D:\python3\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;D:\python3\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;D:\python3\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;D:\python3\lib\site-packages\pluggy\callers.py&quot;, line 208, in _multicall
    return outcome.get_result()
  File &quot;D:\python3\lib\site-packages\pluggy\callers.py&quot;, line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File &quot;D:\python3\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;D:\python3\lib\site-packages\_pytest\main.py&quot;, line 244, in pytest_collection
    return session.perform_collect()
  File &quot;D:\python3\lib\site-packages\_pytest\main.py&quot;, line 437, in perform_collect
    items = self._perform_collect(args, genitems)
  File &quot;D:\python3\lib\site-packages\_pytest\main.py&quot;, line 476, in _perform_collect
    self.items.extend(self.genitems(node))
  File &quot;D:\python3\lib\site-packages\_pytest\main.py&quot;, line 704, in genitems
    yield from self.genitems(subnode)
  File &quot;D:\python3\lib\site-packages\_pytest\main.py&quot;, line 705, in genitems
    node.ihook.pytest_collectreport(report=rep)
  File &quot;D:\python3\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;D:\python3\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;D:\python3\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;D:\python3\lib\site-packages\pluggy\callers.py&quot;, line 208, in _multicall
    return outcome.get_result()
  File &quot;D:\python3\lib\site-packages\pluggy\callers.py&quot;, line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File &quot;D:\python3\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;D:\python3\lib\site-packages\pytest_html\plugin.py&quot;, line 606, in pytest_collectreport
    self.append_failed(report)
  File &quot;D:\python3\lib\site-packages\pytest_html\plugin.py&quot;, line 370, in append_failed
    self._appendrow(&quot;Error&quot;, report)
  File &quot;D:\python3\lib\site-packages\pytest_html\plugin.py&quot;, line 338, in _appendrow
    result = self.TestResult(outcome, report, self.logfile, self.config)
  File &quot;D:\python3\lib\site-packages\pytest_html\plugin.py&quot;, line 164, in __init__
    self.config.hook.pytest_html_results_table_row(report=report, cells=cells)
  File &quot;D:\python3\lib\site-packages\pluggy\hooks.py&quot;, line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File &quot;D:\python3\lib\site-packages\pluggy\manager.py&quot;, line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File &quot;D:\python3\lib\site-packages\pluggy\manager.py&quot;, line 84, in &lt;lambda&gt;
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File &quot;D:\python3\lib\site-packages\pluggy\callers.py&quot;, line 208, in _multicall
    return outcome.get_result()
  File &quot;D:\python3\lib\site-packages\pluggy\callers.py&quot;, line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File &quot;D:\python3\lib\site-packages\pluggy\callers.py&quot;, line 187, in _multicall
    res = hook_impl.function(*args)
  File &quot;D:\PycharmProjects\guest\pyautoTest-master\conftest.py&quot;, line 30, in pytest_html_results_table_row
    cells.insert(2, html.td(report.description))
AttributeError: &apos;CollectReport&apos; object has no attribute &apos;description&apos;</error></testcase></testsuite></testsuites>